### ISSUE TITLE
Issues registering iOS platform key via Safari

### ISSUE THREAD

**Issue by lstoll** [lstoll/webauthn-oidc-idp#22]
```
2022-05-30T16:18:22Z app[1c822c9c] fra [info]2022/05/30 16:18:22 http2: panic serving 145.40.94.31:51042: interface conversion: interface {} is nil, not string
2022-05-30T16:18:22Z app[1c822c9c] fra [info]goroutine 622 [running]:
2022-05-30T16:18:22Z app[1c822c9c] fra [info]net/http.(*http2serverConn).runHandler.func1()
2022-05-30T16:18:22Z app[1c822c9c] fra [info]	/usr/local/go/src/net/http/h2_bundle.go:5896 +0x125
2022-05-30T16:18:22Z app[1c822c9c] fra [info]panic({0xcbc0a0, 0xc000368de0})
2022-05-30T16:18:22Z app[1c822c9c] fra [info]	/usr/local/go/src/runtime/panic.go:838 +0x207
2022-05-30T16:18:22Z app[1c822c9c] fra [info]main.(*webauthnManager).beginRegistration(0xc000080cc0, {0xf35040?, 0xc000336d40}, 0xc0000bf800)
2022-05-30T16:18:22Z app[1c822c9c] fra [info]	/src/webauthn_manager.go:257 +0x946
2022-05-30T16:18:22Z app[1c822c9c] fra [info]net/http.HandlerFunc.ServeHTTP(0xc0003d2990?, {0xf35040?, 0xc000336d40?}, 0xc000063a28?)
2022-05-30T16:18:22Z app[1c822c9c] fra [info]	/usr/local/go/src/net/http/server.go:2084 +0x2f
2022-05-30T16:18:22Z app[1c822c9c] fra [info]net/http.(*ServeMux).ServeHTTP(0xf35c58?, {0xf35040, 0xc000336d40}, 0xc0000bf800)
2022-05-30T16:18:22Z app[1c822c9c] fra [info]	/usr/local/go/src/net/http/server.go:2462 +0x149
2022-05-30T16:18:22Z app[1c822c9c] fra [info]main.baseMiddleware.func1({0xf351c0?, 0xc000011918}, 0xc0000bf700)
2022-05-30T16:18:22Z app[1c822c9c] fra [info]	/src/middleware.go:42 +0x44a
2022-05-30T16:18:22Z app[1c822c9c] fra [info]net/http.HandlerFunc.ServeHTTP(0xc000448974?, {0xf351c0?, 0xc000011918?}, 0x638a66?)
2022-05-30T16:18:22Z app[1c822c9c] fra [info]	/usr/local/go/src/net/http/server.go:2084 +0x2f
2022-05-30T16:18:22Z app[1c822c9c] fra [info]net/http.serverHandler.ServeHTTP({0x0?}, {0xf351c0, 0xc000011918}, 0xc0000bf700)
2022-05-30T16:18:22Z app[1c822c9c] fra [info]	/usr/local/go/src/net/http/server.go:2916 +0x43b
2022-05-30T16:18:22Z app[1c822c9c] fra [info]net/http.initALPNRequest.ServeHTTP({{0xf35c58?, 0xc0003d6b10?}, 0xc00033aa80?, {0xc0002660e0?}}, {0xf351c0, 0xc000011918}, 0xc0000bf700)
2022-05-30T16:18:22Z app[1c822c9c] fra [info]	/usr/local/go/src/net/http/server.go:3523 +0x245
2022-05-30T16:18:22Z app[1c822c9c] fra [info]net/http.(*http2serverConn).runHandler(0xf342e8?, 0x1429cd8?, 0x0?, 0x0?)
2022-05-30T16:18:22Z app[1c822c9c] fra [info]	/usr/local/go/src/net/http/h2_bundle.go:5903 +0x78
2022-05-30T16:18:22Z app[1c822c9c] fra [info]created by net/http.(*http2serverConn).processHeaders
2022-05-30T16:18:22Z app[1c822c9c] fra [info]	/usr/local/go/src/net/http/h2_bundle.go:5633 +0x59b
```

**Comment by lstoll** [comment]
https://github.com/lstoll/webauthn-oidc-idp/blob/ef2203c0634a5b5d5754fcc1f1c727d43cb3820e/webauthn_manager.go#L257

looks like leftover from adding the enroll stuff, this value probably isn't being populated when it's not a bootstrap enrollment.

Intend to clean up the session management anyway, re-visit how data is passed around as part of that.

**Comment by lstoll** [comment]
Aah yeah, it's not even meant to register inline on that page anymore - just redirect to the enroll key page. also

https://github.com/lstoll/webauthn-oidc-idp/blob/ef2203c0634a5b5d5754fcc1f1c727d43cb3820e/webauthn_manager.go#L242-L243

**Comment by lstoll** [comment]
#24 fixed the panic and the registration issues, but iOS safari still has problems.

https://support.yubico.com/hc/en-us/articles/360022004600-No-reaction-when-using-WebAuthn-on-macOS-iOS-and-iPadOS
https://support.yubico.com/hc/en-us/articles/360022004600-No-reaction-when-using-WebAuthn-on-macOS-iOS-and-iPadOS

We may need to add a user-initiating event on these platforms, rather than onLoad. Same will apply to login

https://github.com/keycloak/keycloak/pull/8045
https://github.com/w3c/webauthn/issues/1293

**Comment by lstoll** [comment]
Seems to be resolved in newer iOS
